FROM python:3.11-slim
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
WORKDIR /usr/src/app
COPY client.py utils.py requirements.txt  ./
RUN pip install -r requirements.txt 
EXPOSE 1234
ENV DISPLAY_IMAGES=0
CMD ["python", "client.py", "--host", "server-service.default.svc.cluster.local"]
