apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: nimble-server-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 1235

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - name: media-port
      protocol: TCP
      port: 1235
      targetPort: 1235
